
baseURL = 'https://tuxik.github.io/cuisine/'
languageCode = 'fr-fr'
title = 'La cuisine simple et healthy'
theme = 'lightbi-hugo'
DefaultContentLanguage = "fr"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = false
enableGitInfo = false
pagination.pagerSize = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = false
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = true
description="Your can add your website description here."
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "Tuxik"
  website = ""
  authorInfo = ""
  authorPostImage = ""

[Author]
  name = "Tuxik"
  website = ""
  #email = "donotcontactme@gmail.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #linkedin = "username"
  #github = "username"
  #threads = "username"
  #gitlab = "username"
  #reddit = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #spotify = "username"
  #paypal = "username"
  #telegram = "username"
  #mastodon = "url"
  #slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Notes"
#    url = "/notes/"
#    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

#[[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 4

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 5


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

